---
logging_hosts:
  - address: 192.168.1.3

ntp_hosts:
  - address: 192.168.1.3
    prefer: True
  - address: 192.168.1.4
    prefer: False

tacacs_hosts:
  - address: 192.168.1.3

snmp_ro_acl:
  - seq: 10 
    action: permit
    rule: host 192.168.1.4
  - seq: 20
    action: deny
    rule: any

snmp_rw_acl:
  - seq: 10
    action: permit
    rule: host 192.168.1.3
  - seq: 20
    action: deny
    rule: any

snmp_trap_server: 192.168.1.3
