---
- name: "PLAY 1: Manage Arista Baselines with eos_config"
  hosts: routers
  connection: network_cli
  tasks:
    - name: "TASK 1: Apply EOS Baseline Configurations"
      eos_config:
        src: "{{ item.file }}"
        save_when: changed
      notify: config_changed
      register: cli_result
      when: ansible_network_os == 'eos'
      with_items: "{{ baseline_configs }}"

  handlers:
    - name: "HANDLER 1: Display Updates"
      listen: config_changed
      debug:
        var: item
      loop: "{{ cli_result | json_query('results[*].updates') }}"
      
