---
- name: "PLAY 1: Manage Arista Baselines with eos_config"
  hosts: routers
  connection: network_cli
  tasks:
    - name: "TASK 1: Retrieve platform-specific baseline template"
      set_fact:
        baseline_path: "templates/{{ baseline_config }}.j2"

    - name: "TASK 2: Apply baseline configuration"
      eos_config:
        src: "{{ baseline_path }}"
        save_when: changed
      notify: config_changed
      register: cli_result
      when: ansible_network_os == 'eos'

  handlers:
    - name: "HANDLER 1: Display changes"
      listen: config_changed
      debug:
        msg: "{{ cli_result }}"
