---
- name: "PLAY 1: Verify"
  hosts: routers
  connection: network_cli
  tasks:
    - name: "TASK: Verify Arista Device Baselines"
      include_tasks: eos_verify_tasks.yml
      with_items: "{{ verify_baseline }}"
      loop_control:
        loop_var: verify
